services:
  - type: web
    name: aryabhata
    runtime: docker
    envVars:
      - key: NVIDIA_API_KEY_CHAT
        sync: false
      - key: NVIDIA_API_KEY_CODE
        sync: false
      - key: NVIDIA_API_KEY_IMAGE
        sync: false
      - key: NVIDIA_API_KEY_ROUTER
        sync: false
      - key: NVIDIA_API_KEY_MISTRAL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_JWKS_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
